### ISSUE TITLE
Installation on Debian of node.js

### ISSUE THREAD

**Issue by GregLawson** [codehero/OpenTaxFormFiller#1]
Node.js is in Unstable (aka Sid) on Debian. I was running Stable.
I added to my /etc/apt/sources.lis the following line:
deb http://ftp.us.debian.org/debian sid main
Then I used aptitude to install:
sudo aptitude install nodejs/sid
I rejected the first proposed solution which was full of uninstalls, and selected the second which was full of installs. There were a lot of changes including updating libc6, which required many more unrelated upgrades.

**Comment by codehero** [comment]
For node.js, I just downloaded the stable version and installed it locally into my home directory. I did not attempt to use a package manager.

**Comment by GregLawson** [comment]
That should work too. I prefer using a package manager when it works. I think it limits the number of combinations of configurations to debug a little.
