### ISSUE TITLE
Need Comments with Field Descriptors

### ISSUE THREAD

**Issue by flintiii** [codehero/OpenTaxFormFiller#12]
Greetings,

I am trying this:

`#!/usr/bin/python
# 2017-03-29 09:00:22 pflint
# SOURCE: https://github.com/ccnmtl/fdfgen
from fdfgen import forge_fdf
fields = [
	  ('topmostSubform[0].Page1[0].HeaderPg1[0].f1_01[0]','January'),
	  ('topmostSubform[0].Page1[0].HeaderPg1[0].f1_02[0]','December'),
	  ('topmostSubform[0].Page1[0].HeaderPg1[0].f1_03[0]','16'),
	  ('topmostSubform[0].Page1[0].f1_04[0]','Paul'),
	  ('topmostSubform[0].Page1[0].f1_05[0]','Flint')
	  ]
fdf = forge_fdf("",fields,[],[],[])
fdf_file = open("data.fdf","wb")
fdf_file.write(fdf)
fdf_file.close()
# pdftk f1040.pdf fill_form data.fdf output output.pdf flatten
`

I need to put comments into every entry...

Regards,

flintiii

**Comment by codehero** [comment]
I have not worked on this in years nor has anyone contributed anything. You're on your own, I'm sorry.

**Comment by flintiii** [comment]
Greetings David Bender,

Mind if I fork it and take it over?

Kindest Regards,

Paul Flint


On Sat, 1 Apr 2017, David Bender wrote:

> Date: Sat, 01 Apr 2017 11:44:31 -0700
> From: David Bender <notifications@github.com>
> Reply-To: codehero/OpenTaxFormFiller
>     <reply+000db735b5a3b5f778434e4f5de191918c7a49482e68326892cf0000000114f7b70
>     f92a169ce0cfc76d5@reply.github.com>
> To: codehero/OpenTaxFormFiller <OpenTaxFormFiller@noreply.github.com>
> Cc: Paul Flint <flint@flint.com>, Author <author@noreply.github.com>
> Subject: Re: [codehero/OpenTaxFormFiller] Need Comments with Field Descriptors
>      (#12)
> 
> I have not worked on this in years nor has anyone contributed anything. You're on your own, I'm sorry.
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/codehero/OpenTaxFormFiller/issues/12#issuecomment-290939238

Kindest Regards,



Paul Flint
(802) 479-2360
(802) 595-9365 Cell

/************************************
Based upon email reliability concerns,
please send an acknowledgment in response to this note.

Paul Flint
Barre Open Systems Institute
17 Averill Street
Barre, VT
05641

http://www.bosivt.org
http://family.flint.com/flint
skype: flintinfotech
Work: (202) 537-0480

Consilium                                       _ 
gratuitum        .~.     ASCII ribbon campaign ( )
valet            /V\      against HTML e-mail   X
quanti          /( )\     www.asciiribbon.org  / \ 
numerantur      ^^-^^

**Comment by codehero** [comment]
By all means, please do! Thanks.
