### ISSUE TITLE
Output PDF does not have values filled in.

### ISSUE THREAD

**Issue by GregLawson** [codehero/OpenTaxFormFiller#2]
Needed upgrade of pdftk from version 1.41 to version 1.44.
For Debian see issue #1 for installation from unstable.

**Comment by codehero** [comment]
Could you provide:

1) Your command line invocation
2) a sample .json file

**Comment by GregLawson** [comment]
Upgrading pdftk solved the issue for me. You may want to look into it in more detail as other users may face the same problem.
My original command line was:
./script/fillin_values f1040sa examples/f1040sa.json testing.pdf
I looked at /tmp/output.fdf and since it looked plausible, I entered:
 pdftk 2011/PDF/f1040sa.pdf fill_form /tmp/output.fdf output testing.pdf verbose
Entering evince testing.pdp was also blank.
I checked whether pdftk was miss installed by rerunning [Joe Rothweiler's fdf_gen](https://github.com/GregLawson/fdf_gen) which is similar to OpenFormFiller but hadn't been updated since tax year 2007. It worked fine.
So I went back to OpenFormFiller and tried:
pdftk 2011/PDF/f1040sa.pdf fill_form 2011/field_dump/f1040sa.fdf output Ffields.pdf
It also produced a blank output. I then suspected that the IRS changes from 2007 to 2011 were not being handled well by pdftk so I went to [pdftk version history](http://www.pdflabs.com/docs/pdftk-version-history/) to see if a newer version were available. I had trouble guessing the switch for pdftk to show its version number but eventually stumbled on pdftk --version (not documented in man pdftk or pdftk --help). I was using version 1.41 when I upgraded to version 1.44 by:
sudo apt-get install pdftk/unstable
Then running the previously failing cases above, they both worked correctly.
I did use [beyond compare](http://www.scootersoftware.com/download.php) to try and see if the blank pdf's were really blank or just invisible. My investigation was cursory but I believe they were really blank as the output compared more closely to the input files (seemingly differing only in modification dates) than the expected outputs (way different). To investigate further I would use pdftk to uncompress the pdf inputs and outputs for more meaningful comparisons.

**Comment by NickFenger** [comment]
You can work around this issue by opening the FDF generated by apply_values.js (located at /tmp/output.fdf) using Adobe Reader and specifying the appropriate form in 2011/PDF/ when prompted. Tested under Lucid 10.04 with Adober Reader 9.
