### ISSUE TITLE
json_ots.js reads only lines starting with 'L'

### ISSUE THREAD

**Issue by GregLawson** [codehero/OpenTaxFormFiller#6]
[Open Tax Solver utility](https://github.com/codehero/OpenTaxFormFiller/blob/master/script/json_ots.js) only processes lines starting with 'L'. It would be useful to also handle lines starting with A and D for forms A and D that also appear in the ots 1040.out file. Perhaps add another optional parameter that defaults to L.

**Comment by codehero** [comment]
I added an optional 4th parameter to define the filter prefix. By default, it is "L"
